name: myinfo_v3_sample_webapp
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^7.0.1
  url_strategy: ^0.2.0
  http: ^0.13.6
  basic_utils: ^5.5.4
  jwt_decode: ^0.3.1
  jose: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/cert/
